[versions]
agp = "9.4.1"
kotlin = "2.2.20"
material = "1.10.0"
gdx = "1.14.2"

[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
gdx = { group = "com.badlogicgames.gdx", name = "gdx", version.ref = "gdx" }
gdx-backend-lwjgl3 = { group = "com.badlogicgames.gdx", name = "gdx-backend-lwjgl3", version.ref = "gdx" }
gdx-backend-android = { group = "com.badlogicgames.gdx", name = "gdx-backend-android", version.ref = "gdx" }
gdx-freetype = { group = "com.badlogicgames.gdx", name = "gdx-freetype", version.ref = "gdx" }
gdx-freetype-platform = { group = "com.badlogicgames.gdx", name = "gdx-freetype-platform", version.ref = "gdx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }